package com.company.bookservice.controller;

import com.company.bookservice.models.Book;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.util.List;
@RestController
@RefreshScope
public class BookServiceController {
    //    Create Book
//===========
//    URI: /books
//    HTTP Method: POST
//    RequestBody: Book data (minus ID)
//    ResponseBody: Book data (plus autogenerated ID)
    @RequestMapping(value = "/books", method = RequestMethod.POST)
    @ResponseStatus(HttpStatus.CREATED)
    public Book createBook(@RequestBody Book book) {
        return null;
    }

    //    Get Book
//========
//    URI: /books/{id}
//    HTTP Method: GET
//    RequestBody: None
//    ResponseBody: Book data
    @RequestMapping(value = "/books/{id}", method = RequestMethod.GET)
    @ResponseStatus(HttpStatus.OK)
    public Book getBookById(@PathVariable int id) {
        return null;
    }

    //    Get All Books
//=============
//    URI: /books
//    HTTP Method: GET
//    RequestBody: None
//    ResponseBody: Array of Book data
    @RequestMapping(value = "/books", method = RequestMethod.GET)
    @ResponseStatus(HttpStatus.OK)
    public List<Book> getAllBooks() {
        return null;
    }

    //    Update Book
//===========
//    URI: /books/{id}
//    HTTP Method: PUT
//    RequestBody: Book data
//    ResponseBody: None
    @RequestMapping(value = "/books/{id}", method = RequestMethod.PUT)
    @ResponseStatus(HttpStatus.OK)
    public void updateBook(@PathVariable int id, @RequestBody Book book) {

    }

    //    Delete Book
//===========
//    URI: /books/{id}
//    HTTP Method: DELETE
//    RequestBody: None
//    ResponseBody: None
    @RequestMapping(value = "/books/{id}", method = RequestMethod.DELETE)
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public void deleteBook(@PathVariable int id) {

    }
}
